import 'dart:async';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../../services/savings_service.dart';
import 'savings_event.dart';
import 'savings_state.dart';
import '../../../../models/vault_models.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class SavingsBloc extends Bloc<SavingsEvent, SavingsState> {
  final SavingsService _savingsService;
  StreamSubscription<List<SavingsGoal>>? _goalsSubscription;
  StreamSubscription<List<SavingsLedgerEntry>>? _ledgerSubscription;

  SavingsBloc({required SavingsService savingsService})
      : _savingsService = savingsService,
        super(SavingsInitial()) {
    on<FetchGoalsRequested>(_onFetchGoalsRequested);
    on<GoalsUpdated>(_onGoalsUpdated);
    on<FetchLedgerRequested>(_onFetchLedgerRequested);
    on<LedgerUpdated>(_onLedgerUpdated);
    on<AddContributionRequested>(_onAddContributionRequested);
    on<CreateGoalRequested>(_onCreateGoalRequested);
  }

  Future<void> _onFetchGoalsRequested(FetchGoalsRequested event, Emitter<SavingsState> emit) async {
    emit(SavingsLoading());
    await _goalsSubscription?.cancel();
    _goalsSubscription = _savingsService.watchGoals().listen(
      (goals) => add(GoalsUpdated(goals)),
      onError: (error) => emit(SavingsError(error.toString())),
    );
  }

  void _onGoalsUpdated(GoalsUpdated event, Emitter<SavingsState> emit) {
    if (state is SavingsLoaded) {
      final currentState = state as SavingsLoaded;
      emit(SavingsLoaded(
        goals: event.goals,
        selectedGoalLedger: currentState.selectedGoalLedger,
      ));
    } else {
      emit(SavingsLoaded(goals: event.goals));
    }
  }

  Future<void> _onFetchLedgerRequested(FetchLedgerRequested event, Emitter<SavingsState> emit) async {
    await _ledgerSubscription?.cancel();
    _ledgerSubscription = _savingsService.watchLedger(event.goalId).listen(
      (ledger) => add(LedgerUpdated(ledger)),
      onError: (error) {
        if (state is SavingsLoaded) {
          final currentState = state as SavingsLoaded;
          emit(SavingsLoaded(goals: currentState.goals, error: error.toString()));
        }
      },
    );
  }

  void _onLedgerUpdated(LedgerUpdated event, Emitter<SavingsState> emit) {
    if (state is SavingsLoaded) {
      final currentState = state as SavingsLoaded;
      emit(SavingsLoaded(
        goals: currentState.goals,
        selectedGoalLedger: event.ledger,
      ));
    }
  }

  Future<void> _onAddContributionRequested(AddContributionRequested event, Emitter<SavingsState> emit) async {
    try {
      await _savingsService.addContribution(
        goal: event.goal,
        amount: event.amount,
        source: event.source,
      );
      // Success will be reflected via the real-time stream
    } catch (e) {
      if (state is SavingsLoaded) {
        final currentState = state as SavingsLoaded;
        emit(SavingsLoaded(goals: currentState.goals, selectedGoalLedger: currentState.selectedGoalLedger, error: e.toString()));
      } else {
        emit(SavingsError(e.toString()));
      }
    }
  }

  Future<void> _onCreateGoalRequested(CreateGoalRequested event, Emitter<SavingsState> emit) async {
    try {
      final userId = Supabase.instance.client.auth.currentUser?.id;
      if (userId == null) throw Exception('User not authenticated');

      final newGoal = SavingsGoal(
        id: '', // Will be generated by DB
        userId: userId,
        title: event.title,
        targetAmount: event.targetAmount,
        currentAmount: 0.0,
        deadlineDate: event.deadline,
        status: 'active',
      );

      await _savingsService.createGoal(newGoal);
    } catch (e) {
      if (state is SavingsLoaded) {
        final currentState = state as SavingsLoaded;
        emit(SavingsLoaded(goals: currentState.goals, selectedGoalLedger: currentState.selectedGoalLedger, error: e.toString()));
      } else {
        emit(SavingsError(e.toString()));
      }
    }
  }

  @override
  Future<void> close() {
    _goalsSubscription?.cancel();
    _ledgerSubscription?.cancel();
    return super.close();
  }
}
